DROP DATABASE IF EXISTS Shortenpydb;

CREATE DATABASE Shortenpydb
	CHARACTER SET utf8mb4
    COLLATE utf8mb4_general_ci;

USE Shortenpydb;

CREATE TABLE Shortenpy (
    id INT PRIMARY KEY AUTO_INCREMENT,
    date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    name VARCHAR(127) NOT NULL,
    link TEXT NOT NULL,
    short VARCHAR(127) NOT NULL,
    expire DATETIME DEFAULT NULL,
    views INT DEFAULT '0'
);

DELIMITER //

CREATE TRIGGER set_expire_before_insert
BEFORE INSERT ON redir
FOR EACH ROW
BEGIN
    SET NEW.expire = DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 YEAR);
END;

//

DELIMITER ;